version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: lifeontrack-mysql
        environment:
            MYSQL_DATABASE: lifeontrack-dev
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports: 
            - "3307:3307"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    mysql_data:
        driver: local
