service: life-on-track-api

provider:
   name: aws
   runtime: python3.9
   region: us-east-2

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - node_modules/**
    - venv/**

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-east-1

functions: ${file(./functions.yml)}
